scan_filter_chain:
- name: box
  type: laser_filters/LaserScanBoxFilter
  params:
    box_frame: base_link
    min_x: -0.14184
    max_x: 0.14184
    min_y: -0.2
    max_y: 0.25
    min_z: 0.1
    max_z: 0.5


