# planners:
#   # LOCAL
#   - name: 'TrajectoryPlannerROS'
#     type: 'base_local_planner/TrajectoryPlannerROS'
#   # GLOBAL
#   - name: 'NavfnROS'
#     type: 'navfn/NavfnROS'
controllers:
  - name: 'TrajectoryPlannerROS'
    type: 'base_local_planner/TrajectoryPlannerROS'
controller:
  holonomic_robot: false

planners:
  # # LOCAL
  # - name: 'TrajectoryPlannerROS'
  #   type: 'base_local_planner/TrajectoryPlannerROS'

  # GLOBAL
  - name: 'NavfnROS'
    type: 'navfn/NavfnROS'

mbf_tolerance_check: true
dist_tolerance: 0.2
angle_tolerance: 1.5

# do not change below values

controller_frequency: 5.0
controller_patience: 3.0

planner_frequency: 1.0
planner_patience: 5.0

oscillation_timeout: 10.0
oscillation_distance: 0.2

mbf_tolerance_check: true
dist_check: 0.2
angle_tolerance: 1.5

base_local_planner: "base_local_planner/TrajectoryPlannerROS"
base_global_planner: "navfn/NavfnROS"
